permission:
  Comment:
    - create
    - update
    - destroy
  Shop:
    - update
    - destroy
  Product:
    - create
    - update
    - destroy
  OrderTransaction:
    - create
    - update
    - read
  Category:
    - create
    - update
    - destroy
  ShopUser:
    - create
    - destroy
  ShopGroup:
    - create
    - destroy

group_permission:
  sale:
    OrderTransaction:
      - create
      - read

  inventory:
    OrderTransaction:
      - update
      - read